version: "3.9"

services:
    # web:
    #     build: .
    #     ports:
    #         - "8000:80"
    #     depends_on:
    #         - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:  
          - "1433:1433"
        environment:
            SA_PASSWORD: "32801f61-7582-46fb-a390-afd39a11096b"
            ACCEPT_EULA: "Y"

networks:
  db_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.17/24"