# Generated by Django 3.2.8 on 2021-10-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
