# Generated by Django 3.2.8 on 2021-10-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='path',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
