# Generated by Django 3.2.8 on 2021-10-17 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='From'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='responsibility',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='To'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='abount_me',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduce',
            field=models.CharField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience_month', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.categoryskill')),
            ],
        ),
        migrations.AddField(
            model_name='categoryskill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.profile'),
        ),
    ]
